/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * Stable string codes for operational (non-validation) issues.
 *
 * Used by IssueFactory methods and consumed by the API-layer HTTP-status
 * resolver so the two places stay in sync without repeating string literals.
 */
export const ISSUE_CODE = {
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  TRANSIENT_DB_READ_FAILED: 'TRANSIENT_DB_READ_FAILED',
  USECASE_CHANGE_PROJECTION_FAILED: 'USECASE_CHANGE_PROJECTION_FAILED',
  PARSE_ERROR: 'PARSE_ERROR',
  PARAM_PAYLOAD_NOT_FOUND: 'PARAM_PAYLOAD_NOT_FOUND',
  PROPERTY_PAYLOAD_NOT_FOUND: 'PROPERTY_PAYLOAD_NOT_FOUND',
  PARAM_READ_ONLY: 'PARAM_READ_ONLY',
  PARAM_SERIALIZATION_FAILED: 'PARAM_SERIALIZATION_FAILED',
  SESSION_NOT_OPEN: 'SESSION_NOT_OPEN',
  SESSION_MODE_NOT_ALLOWED: 'SESSION_MODE_NOT_ALLOWED',
  ROUTING_PREVAL_SCOPE_INCOMPLETE: 'ARC-ROUTING-PREVAL-SCOPE-INCOMPLETE',
  ROUTING_PREVAL_DUPLICATE_ACTIVE_SUBGRAPH_SELECTION:
    'ARC-ROUTING-PREVAL-DUPLICATE-ACTIVE-SUBGRAPH-SELECTION',
  ROUTING_PREVAL_EDIT_SCOPE_CONFLICT: 'ARC-ROUTING-PREVAL-EDIT-SCOPE-CONFLICT',
  ROUTING_PREVAL_DATALINK_INTEGRITY: 'ARC-ROUTING-PREVAL-DATALINK-INTEGRITY',
  ROUTING_ISLAND_DETECTED: 'ARC-ROUTING-ISLAND-DETECTED',
  ROUTING_DELETION_SELECTION_REQUIRED: 'ARC-ROUTING-DEL-02',
  ROUTING_UC_AUTO_ISLAND: 'ARC-ROUTING-UC-AUTO-ISLAND',
  ROUTING_SGKV_MALFORMED: 'ARC-ROUTING-SGKV-MALFORMED',
  ROUTING_SGKV_VALUE_NOT_FOUND: 'ARC-ROUTING-SGKV-VALUE-NOT-FOUND',
  ROUTING_CYCLE_DETECTED: 'ARC-ROUTING-CYCLE-DETECTED',
  ROUTING_DFS_NO_VALID_COMBINATION: 'ARC-ROUTING-DFS-08',
  // Module write path — structural validation
  MOD_CONTAINER_TYPE_INCOMPATIBLE: 'ARC-MOD-CONTAINER-TYPE-INCOMPATIBLE',
  MOD_CONTAINER_PROP_MISMATCH: 'ARC-MOD-CONTAINER-PROP-MISMATCH',
  MOD_SUBGRAPH_IMPORTED: 'ARC-MOD-SUBGRAPH-IMPORTED',
  MOD_PORT_COUNT_EXCEEDS_DEFINITION: 'ARC-MOD-PORT-COUNT-EXCEEDS-DEFINITION',
  MOD_PORT_COUNT_DECREASE_BLOCKED: 'ARC-MOD-PORT-COUNT-DECREASE-BLOCKED',
  MOD_NO_AVAILABLE_INTENTS: 'ARC-MOD-NO-AVAILABLE-INTENTS',
  MOD_PORT_COUNT_BELOW_STATIC_MINIMUM:
    'ARC-MOD-PORT-COUNT-BELOW-STATIC-MINIMUM',
  SS_NOT_EMPTY: 'ARC-SS-NOT-EMPTY',
  SS_DUPLICATE_NAME: 'ARC-SS-DUPLICATE-NAME',
  SS_CIRCULAR_HIERARCHY: 'ARC-SS-CIRCULAR-HIERARCHY',
  SS_DUPLICATE_CHILD: 'ARC-SS-DUPLICATE-CHILD',
} as const;

export type IssueCode = (typeof ISSUE_CODE)[keyof typeof ISSUE_CODE];
