/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * Stable string codes for operational (non-validation) issues.
 *
 * Used by IssueFactory methods and consumed by the API-layer HTTP-status
 * resolver so the two places stay in sync without repeating string literals.
 */
export const ISSUE_CODE = {
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  PARSE_ERROR: 'PARSE_ERROR',
  PARAM_PAYLOAD_NOT_FOUND: 'PARAM_PAYLOAD_NOT_FOUND',
  SESSION_NOT_OPEN: 'SESSION_NOT_OPEN',
  SESSION_MODE_NOT_ALLOWED: 'SESSION_MODE_NOT_ALLOWED',
  // Module write path — structural validation
  MOD_CONTAINER_TYPE_INCOMPATIBLE: 'ARC-MOD-CONTAINER-TYPE-INCOMPATIBLE',
  MOD_CONTAINER_PROP_MISMATCH: 'ARC-MOD-CONTAINER-PROP-MISMATCH',
  MOD_PORT_COUNT_EXCEEDS_DEFINITION: 'ARC-MOD-PORT-COUNT-EXCEEDS-DEFINITION',
  MOD_PORT_COUNT_DECREASE_BLOCKED: 'ARC-MOD-PORT-COUNT-DECREASE-BLOCKED',
  MOD_NO_AVAILABLE_INTENTS: 'ARC-MOD-NO-AVAILABLE-INTENTS',
  MOD_PORT_COUNT_BELOW_STATIC_MINIMUM:
    'ARC-MOD-PORT-COUNT-BELOW-STATIC-MINIMUM',
  // Control link write path
  CL_SELF_LOOP: 'ARC-CL-SELF-LOOP',
  CL_SUBSYSTEM_FLAT_VIEW: 'ARC-CL-SUBSYSTEM-FLAT-VIEW',
  CL_DUPLICATE: 'ARC-CL-DUPLICATE',
  CL_EMPTY_INTENT_INTERSECTION: 'ARC-CL-EMPTY-INTENT-INTERSECTION',
  CL_USECASE_MISMATCH: 'ARC-CL-USECASE-MISMATCH',
  CL_SUBSYSTEM_PORT_SIDE_CONFLICT: 'ARC-CL-SUBSYSTEM-PORT-SIDE-CONFLICT',
} as const;

export type IssueCode = (typeof ISSUE_CODE)[keyof typeof ISSUE_CODE];
