/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 */

import type {ActiveSession} from './active-session.js';

/**
 * Ambient in-request write context held on UnitOfWork.
 * Stamped once by CommandBus after session/mode checks pass (§8.2 of
 * foundation.md). Consumers (handlers, edit-repo adapters, PendingChangeWriter)
 * read it via uow.getWriteContext() — never mutate it mid-request.
 *
 * `source` is intentionally NOT here: nested services within one request may
 * produce writes with different sources, so source travels per-write via the
 * edit-repo options bag (§8.1 of foundation.md).
 */
export type WriteContext = {
  /** The active session resolved by SessionGuard. */
  session: ActiveSession;
  /** UUID generated by CommandBus — one value per CommandBus.execute() call.
   *  All edit_actions rows written within one API call share this groupId,
   *  enabling atomic undo/redo/stage/unstage (REQ-ATO-01 to REQ-ATO-05). */
  groupId: string;
};
